version: '2'
services:
  assets:
    build:
      context: ./assets/
    restart: always
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./assets/:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - PORT=8002
    ports:
      - "10002:8002"
  backend:
    build:
      context: ./backend/
    restart: always
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - PORT=8001
      - API_URL=api.dev.grocock.email
    ports:
      - "10001:8001"
    depends_on:
      - db
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend/
    command: npm run prod
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
      - db
    ports:
      - "10000:5000"
  db:
    image: "postgres:11"
    container_name: "db"
    restart: always
    ports:
      - "10003:5432"
    environment:
      - POSSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
volumes:
  data: