version: '2'
services:
  assets:
    build:
      context: ./assets/
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./assets/:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - DEBUG=express:*
      - CHOKIDAR_USEPOLLING=true
      - PORT=8080
    labels:
      - "traefik.frontend.rule=Host:assets.grocock.email"
      - "traefik.port=8080"
      - "traefik.docker.network=front"
    networks:
      - front
  backend:
    build:
      context: ./backend/
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=8080
      - API_URL=api.grocock.email
    labels:
      - "traefik.frontend.rule=Host:api.grocock.email"
      - "traefik.port=5000"
    depends_on:
      - db
    networks: 
      - backend
      - proxy
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    labels:
      - "traefik.frontend.rule=Host:grocock.email"
      - "traefik.port=3000"
    depends_on:
      - backend
      - db
    networks:
      - proxy
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
    networks:
        - backend
volumes:
  data:
networks: 
  backend:
    internal: true
  proxy:
    external: true