# This is a basic workflow to help you get started with Actions

name: Test PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: grocock.email
        
      - name: Clone Dev changes
        run: ssh staging 'cd /root/website/website_dev; git checkout ${ GITHUB_HEAD_REF }; git pull'
      - name: Build Dev changes
        run: ssh server 'cd /root/website/website_dev; docker-compose -f "./docker-compose.dev.yml" up -d'
      
      - name: Sleep for 1 minute
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      
      - name: Check http status code of Development site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["https://dev.grocock.email"]'
          expected: '[200]'
